name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'
      - repo: https://github.com/astral-sh/ruff-pre-commit
        # Ruff version.
        rev: v0.5.6
        hooks:
          # Run the linter.
          - id: ruff
          # Run the formatter.
          - id: ruff-format







