name: Lint and Format

on: [push]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyflakes black

    - name: Run linter
      run: |
        pyflakes .
      
    - name: Run formatter
      run: |
        black .

    - name: Check if there are changes
      id: check_changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git diff --cached --quiet || echo "Changes detected"

    - name: Commit and push changes
      if: steps.check_changes.outputs.changes_detected == 'Changes detected'
      run: |
        git commit -m "Autoformatted code"
        git push



