name: Lint and Format

on: [push]

jobs:
  setup-project:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff

  lint-and-format:
    runs-on: ubuntu-latest
    needs: setup-project

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff
   
    - name: Run linter
      run: |
        ruff check $(git ls-files '*.py')
      
    - name: Run formatter
      run: |
        ruff format $(git ls-files '*.py')

  publish:
    runs-on: ubuntu-latest
    needs: lint-and-format
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # fetch all history for commits to push

    - name: Create local changes
      run: |
        # Verifique se há arquivos modificados
        git status

    - name: Commit & Push changes
      uses: EndBug/add-and-commit@v9
      with:
        author_name: 'github-actions[bot]'
        author_email: 'github-actions[bot]@users.noreply.github.com'
        message: 'Autoformatted code with ruff'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


