name: Lint and Format Code

on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Python Linter
        uses: sunnysid3up/python-linter@v0.1-beta.7

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          commit_message: "chore: Format code with Black"
          branch: ${{ github.head_ref }}


